version: '3.4'

services:
  webclient:
    image: parcheesi/pwaspaclient
    build:
      context: .
      dockerfile: WebClient/Dockerfile
    depends_on:
     - gatewayapi

  pwaspaclient:
    image: parcheesi/pwaspaclient
    build:
      context: .
      dockerfile: Clients/PwaSpaClient/Dockerfile
    depends_on:
     - gatewayapi

  gatewayapi:
    image: parcheesi/gatewayapi
    build:
      context: .
      dockerfile: GatewayApi/Dockerfile
    depends_on:
      - identityservice
      - networkservice
      - gameservice
      - contentservice
      - chatservice

  identityservice:
    image: parcheesi/identityservice
    build:
      context: .
      dockerfile: IdentityService/Dockerfile
    depends_on:
      - mongo

  networkservice:
    image: parcheesi/networkservice
    build:
      context: .
      dockerfile: NetworkService/Dockerfile
    depends_on:
      - mongo


  gameservice:
    image: parcheesi/gameservice
    build:
      context: .
      dockerfile: GameService/Dockerfile
    depends_on:
      - mongo


  contentservice:
    image: parcheesi/contentservice
    build:
      context: .
      dockerfile: ContentService/Dockerfile
    depends_on:
      - mongo


  chatservice:
    image: parcheesi/chatservice
    build:
      context: .
      dockerfile: ChatService/Dockerfile
    depends_on:
      - mongo

  mongo:
    image: mongo
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3

